name: squad_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  http: ^1.2.2
  desktop_window: ^0.4.2
  flutter_svg: ^2.0.14
  get_it: ^8.0.2
  loading_animation_widget: ^1.3.0
  awesome_snackbar_content: ^0.1.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter    

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  http_mock_adapter: ^0.6.1


flutter:
  uses-material-design: true


  assets:
    - assets/readme/
    - assets/animations/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets\fonts\Kanit-Thin.ttf
          weight: 100
        - asset: assets\fonts\Kanit-ExtraLight.ttf
          weight: 200
        - asset: assets\fonts\Kanit-Light.ttf
          weight: 300       
        - asset: assets\fonts\Kanit-Regular.ttf
          style: normal   
        - asset: assets\fonts\Kanit-Medium.ttf
          weight: 500       
        - asset: assets\fonts\Kanit-SemiBold.ttf
          weight: 600    
        - asset: assets\fonts\Kanit-Bold.ttf
          weight: 700      
        - asset: assets\fonts\Kanit-ExtraBold.ttf
          weight: 800     
        - asset: assets\fonts\Kanit-Black.ttf
          weight: 900                                                                   